spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    default-property-inclusion: non_null
# redis:
#   host: 192.168.30.113
#   port: 6379

#server:
#   context-path: /index
#   error:
#     path: /error
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml




server:
  session:
    timeout: -1
  port: 8886


Intro:
   synchUrl: https://bbk.800app.com/uploadfile/staticresource/238592/279833/dataInterface_intro.aspx



