spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
# jackson:
#   default-property-inclusion: non_null
# redis:
#   host: 192.168.30.113
#   port: 6379

#server:
#   context-path: /index
#   error:
#     path: /error


mail_appid : 10034
mail_appkey : 6e88cf3e26b914c70b9e57b5ebb26b21
mail_signtype : md5
msg_appid : 13698
msg_appkey : 3877871b96eac711ed8a76e286df30bc
msg_signtype : normal


##httpclient
#最大连接数
http.maxTotal : 50000
#并发数
http.defaultMaxPerRoute : 10000
#创建连接的最长时间
http.connectTimeout: 15000
#从连接池中获取到连接的最长时间
http.connectionRequestTimeout: 15000
#数据传输的最长时间
http.socketTimeout: 25000
#提交请求前测试连接是否可用
http.staleConnectionCheckEnabled: true
server:
  session:
    timeout: -1






